/* Put db schema here*/
CREATE TABLE `Employee` (
  `ID`   INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `NAME` VARCHAR(100)     NOT NULL,
/*`AGE` INT(10) UNSIGNED NOT NULL, */
  PRIMARY KEY (`ID`)
)
  ENGINE =InnoDB
  AUTO_INCREMENT =1
  DEFAULT CHARSET =utf8;


